IT3_ImoGest/ImoGest/ViewModels/RealEstateViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ImoGestClient.ViewModels
{
    public class RealEstateViewModels
    {
        public int ID { get; set; }
        [Display(Name = "Descrição do Imóvel"), Required, StringLength(120, MinimumLength = 8)]
        public string Description { get; set; }

        [Display(Name = "Localização")]
        public virtual LocalizationViewModels Localization { get; set; }

        [Display(Name = "Tipo de Imóvel")]
        public int TypologyID { get; set; }
        public virtual RealEstateTypologyViewModels Typology { get; set; }

        [Display(Name = "Área"), Required]
        [Range(0.0, Double.MaxValue, ErrorMessage = "Invalid area value")]
        public double Area { get; set; }

        [Display(Name = "Fotografias")]
        public virtual ICollection<PhotoViewModels> Photos { get; set; }

        [ForeignKey("Owner")]
        public string OwnerID { get; set; }
        public virtual ApplicationUserViewModels Owner { get; set; }
    }
}

IT3_ImoGest/ImoGest/Controllers/RealEstatesController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Infrastructure;
using Microsoft.AspNet.Identity;
using ImoGestClient.Models;
using ImoGestClient.ViewModels;

namespace ImoGestClient.Controllers
{
    [Authorize(Roles = UserRolesApi.Client)]
    public class RealEstatesController : MainController
    {
        // GET: RealEstates
        public ActionResult Index()
        {
            if (!UnitOfWork.Authorizations.RealEstate.allowView())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(UnitOfWork.Repositories.RealEstates.All());
        }

        // GET: RealEstates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealEstateViewModels realEstate = UnitOfWork.Repositories.RealEstates.GetById((int)id);
            if (realEstate == null)
            {
                return HttpNotFound();
            }
            if (!UnitOfWork.Authorizations.RealEstate.allowDetails(realEstate))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(realEstate);
        }

        // GET: RealEstates/Create
        public ActionResult Create()
        {
            if (!UnitOfWork.Authorizations.RealEstate.allowAdd())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            ViewBag.TypologyID = new SelectList(UnitOfWork.Repositories.RealEstateTypologies.All(), "ID", "FullDescription").ToList();
            return View();
        }

        // POST: RealEstates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "ID,Description,TypologyID,Area")] RealEstateViewModels realEstate, 
            [Bind(Include = "ID,Latitude,Longitude")] LocalizationViewModels localization, 
            IEnumerable<HttpPostedFileBase> uploads
            ) {

            if (!UnitOfWork.Authorizations.RealEstate.allowAdd())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            try
            {
                if (ModelState.IsValid)
                {
                    realEstate.Photos = new List<PhotoViewModels>();

                    foreach (var upload in uploads)
                    {
                        if (upload != null && upload.ContentLength > 0)
                        {
                            var photo = new PhotoViewModels
                            {
                                PhotoName = System.IO.Path.GetFileName(upload.FileName),
                                ContentType = upload.ContentType
                            };
                            using (var reader = new System.IO.BinaryReader(upload.InputStream))
                            {
                                photo.Content = reader.ReadBytes(upload.ContentLength);
                            }
                            realEstate.Photos.Add(photo);
                        }
                    }

                    localization.RealEstate = realEstate;
                    realEstate.Localization = localization;
                    realEstate.OwnerID = User.Identity.GetUserId();

                    UnitOfWork.Repositories.RealEstates.Add(realEstate);
                    UnitOfWork.Save();

                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            ViewBag.TypologyID = new SelectList(UnitOfWork.Repositories.RealEstateTypologies.All(), "ID", "FullDescription");
            return View(realEstate);
        }

        // GET: RealEstates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealEstateViewModels realEstate = UnitOfWork.Repositories.RealEstates.GetById((int) id);

            if (realEstate == null)
            {
                return HttpNotFound();
            }

            if (!UnitOfWork.Authorizations.RealEstate.allowEdit(realEstate))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            
            ViewBag.TypologyID = new SelectList(UnitOfWork.Repositories.RealEstateTypologies.All(), "ID", "FullDescription");
            return View(realEstate);
        }

        
        // POST: RealEstates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,TypologyID,Area,OwnerID")] RealEstateViewModels realEstate,
            [Bind(Include = "Latitude,Longitude")] LocalizationViewModels localization,
            IEnumerable<HttpPostedFileBase> uploads)
        {
            if (!UnitOfWork.Authorizations.RealEstate.allowEdit(realEstate))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            try
            {
                if (ModelState.IsValid)
                {
                    var realEstateOnDB = UnitOfWork.Repositories.RealEstates.GetById(realEstate.ID);

                    if (uploads?.FirstOrDefault() != null)
                    {
                        UnitOfWork.Repositories.RealEstates.Remove(realEstateOnDB);
                        UnitOfWork.Save();

                        realEstateOnDB.Photos = new List<PhotoViewModels>();

                        foreach (var upload in uploads)
                        {
                            if (upload != null && upload.ContentLength > 0)
                            {
                                var photo = new PhotoViewModels
                                {
                                    PhotoName = System.IO.Path.GetFileName(upload.FileName),
                                    ContentType = upload.ContentType
                                };
                                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                                {
                                    photo.Content = reader.ReadBytes(upload.ContentLength);
                                }
                                realEstateOnDB.Photos.Add(photo);
                            }
                        }

                        UnitOfWork.Repositories.RealEstates.Add(realEstateOnDB);
                        UnitOfWork.Save();
                    } else
                    {
                        realEstateOnDB.Area = realEstate.Area;
                        realEstateOnDB.Description = realEstate.Description;
                        realEstateOnDB.Localization.Latitude = localization.Latitude;
                        realEstateOnDB.Localization.Longitude = localization.Longitude;
                        realEstateOnDB.Typology = realEstate.Typology;
                        UnitOfWork.Repositories.RealEstates.Edit(realEstateOnDB);
                    }

                    return RedirectToAction("Index");
                }

                ViewBag.TypologyID = new SelectList(UnitOfWork.Repositories.RealEstateTypologies.All(), "ID", "FullDescription");
                return View(realEstate);
            }
            catch(RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            return View(realEstate);
        }

        // GET: RealEstates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RealEstateViewModels realEstate = UnitOfWork.Repositories.RealEstates.GetById((int)id);
            if (realEstate == null)
            {
                return HttpNotFound();
            }

            if (!UnitOfWork.Authorizations.RealEstate.allowDelete(realEstate))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(realEstate);
        }

        // POST: RealEstates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RealEstateViewModels realEstate = UnitOfWork.Repositories.RealEstates.GetById(id);
            if (realEstate == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!UnitOfWork.Authorizations.RealEstate.allowDelete(realEstate))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            UnitOfWork.Repositories.RealEstates.Remove(realEstate);
            UnitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

IT3_ImoGest/ImoGest/Views/RealEstates/Create.cshtml
@model ImoGestClient.ViewModels.RealEstateViewModels

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "RealEstates", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RealEstate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypologyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypologyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypologyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Localization.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localization.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localization.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Localization.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localization.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localization.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width: 280px;">
                    @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">m^<small>2</small></span>
                </div>
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="multiple">
                    <input type="file" id="Photo" class="multiple" name="uploads" multiple required/>
                </div>
                <div id="single">
                    <input type="file" class="single" name="uploads" required/><br />
                    <input type="file" class="single" name="uploads" /><br />
                    <input type="file" class="single" name="uploads" /><br />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
            if(window.FileReader != null){
                $('#single').hide();
                $('.single').prop('disabled', true);
            } else {
                $('#multiple').hide();
                $('.multiple').prop('disabled', true);
            }
        });
    </script>
}

IT3_ImoGest/ImoGest/Views/RealEstates/Delete.cshtml
@model ImoGestClient.ViewModels.RealEstateViewModels

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RealEstate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Typology.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Typology.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area) m^2
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Localization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Localization.Coordinates)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IT3_ImoGest/ImoGest/Views/RealEstates/Details.cshtml
@model ImoGestClient.ViewModels.RealEstateViewModels

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RealEstate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Typology.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Typology.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Area) m^2
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Localization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Localization.Coordinates)
        </dd>

        @if (Model.Photos.Any(p => p.RealEstateID == Model.ID))
        {
        <dt>
            @Html.DisplayNameFor(model => model.Photos)
        </dt>

        <dd>
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Photos.Count; i++)
                    {
                        <li data-target="#myCarousel" class="active" data-slide-to="@i"></li>
                    }
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="~/Photos?id=@Model.Photos.First().PhotoID" alt="RealEstatePhoto" class="img-responsive"/>
                    </div>
                    @foreach(var photo in Model.Photos)
                    {
                        if (!photo.Equals(Model.Photos.First())) {
                            <div class="item">
                                <img src="~/Photos?id=@photo.PhotoID" alt="RealEstatePhoto" class="img-responsive" />
                            </div>
                        }
                    }
               </div>
            </div>
        </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IT3_ImoGest/ImoGest/Views/RealEstates/Edit.cshtml
@model ImoGestClient.ViewModels.RealEstateViewModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","RealEstates", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RealEstate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.OwnerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypologyID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypologyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypologyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Localization.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localization.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localization.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Localization.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Localization.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Localization.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" style="width: 280px;">
                    @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">m^<small>2</small></span>
                </div>
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="multiple">
                    <input type="file" id="Photo" class="multiple" name="uploads" multiple />
                </div>
                <div id="single">
                    <input type="file" class="single" name="uploads" /><br />
                    <input type="file" class="single" name="uploads" /><br />
                    <input type="file" class="single" name="uploads" /><br />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
            if(window.FileReader != null){
                $('#single').hide();
                $('.single').prop('disabled', true);
            } else {
                $('#multiple').hide();
                $('.multiple').prop('disabled', true);
            }
        });
    </script>
}

IT3_ImoGest/ImoGest/Views/RealEstates/Index.cshtml
@model IEnumerable<ImoGestClient.ViewModels.RealEstateViewModels>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Typology.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Localization)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photos)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Typology.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Localization.Coordinates)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photos.Count) inseridas
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>